spring:
  application:
    name: AiTaskApp
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none 
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    table: flyway_schema_history

jwt:
  public:
    key: classpath:/app.pub
  private:
    key: classpath:/app.key
  issuer: ai-powered-task-app
  token-expiry: 1800
  refresh-token-expiry: 604800